export const targetMock =       
{
    "code":0,
    "error":"success",
    "data":{
        "title":"目标跟踪",
        "sub_title":"小米商城",
        "progress":"时间进度66%",
        "track_tbl":{
            "header":[
                {
                    "label":"品类",
                    "value":"cat"
                },
                {
                    "label":"月目标",
                    "value":"target"
                },
                {
                    "label":"月达成",
                    "value":"complete"
                },
                {
                    "label":"达成率",
                    "value":"rate"
                },
                {
                    "label":"月同比",
                    "value":"yoy"
                }
            ],
            "body":[
                {
                    "complete":0.721,
                    "cells":[
                        {
                            "val":0,
                            "val_desc":"手机",
                            "val_type":"text"
                        },
                        {
                            "val":132131,
                            "val_desc":"13.2万件",
                            "val_type":"number"
                        },
                        {
                            "val":102318,
                            "val_desc":"10.2万件",
                            "val_type":"text"
                        },
                        {
                            "val":0.721,
                            "val_desc":"72.1%",
                            "val_type":"ratio"
                        },
                        {
                            "val":0.023,
                            "val_desc":"2.3%",
                            "val_type":"ratio"
                        }
                    ]
                },
                {
                    "complete":0.871,
                    "cells":[
                        {
                            "val":0,
                            "val_desc":"电视",
                            "val_type":"text"
                        },
                        {
                            "val":82131,
                            "val_desc":"8.2万件",
                            "val_type":"number"
                        },
                        {
                            "val":72318,
                            "val_desc":"7.2万件",
                            "val_type":"text"
                        },
                        {
                            "val":0.871,
                            "val_desc":"87.1%",
                            "val_type":"ratio"
                        },
                        {
                            "val":0.052,
                            "val_desc":"5.2%",
                            "val_type":"ratio"
                        }
                    ]
                },
                {
                    "complete":0.432,
                    "cells":[
                        {
                            "val":0,
                            "val_desc":"笔记本",
                            "val_type":"text"
                        },
                        {
                            "val":50000,
                            "val_desc":"5万件",
                            "val_type":"number"
                        },
                        {
                            "val":24318,
                            "val_desc":"2.4万件",
                            "val_type":"text"
                        },
                        {
                            "val":0.432,
                            "val_desc":"43.2%",
                            "val_type":"ratio"
                        },
                        {
                            "val":-0.013,
                            "val_desc":"-1.3%",
                            "val_type":"ratio"
                        }
                    ]
                }
            ]
        }
    }
}